language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest --cov=arctic_tern/

after_success:
  - codecov