language: python
python:
  - "3.8"

before_install:
- pip install poetry

# command to install dependencies
install:
  - poetry install -v -E psycopg -E asyncpg
  - poetry install codecov

# command to run tests
script:
  - poetry run pytest --cov=arctic_tern/

after_success:
  - poetry run codecov